import httpx
import os
import re
import json

from urllib.parse import urljoin
from typing import Any, Dict, Optional
from mcp.server.fastmcp import FastMCP, Context

# Initialize FastMCP server
mcp = FastMCP("fraudlabspro")

# Constants
FLP_API_BASE = "https://api.fraudlabspro.com/v2/"
USER_AGENT = "fraudlabspro-app/1.0"

def get_api_key() -> str | None:
    """Retrieve the API key from MCP server config."""
    return os.getenv("FRAUDLABSPRO_API_KEY")

async def make_request(url: str, params: dict[str, str]) -> dict[str, Any] | None:
    """Make a request to the IP2Location.io API with proper error handling."""
    headers = {
        "User-Agent": USER_AGENT,
        "Accept": "application/json"
    }
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, headers=headers, params=params, timeout=30.0)
            response.raise_for_status()
            return response.json()
        except Exception:
            return None

async def make_request_post(url: str, data: dict[str, str]) -> dict[str, Any] | None:
    """Make a request to the IP2Location.io API with proper error handling."""
    headers = {
        "User-Agent": USER_AGENT,
        "Accept": "application/json"
    }
    payload_data = json.dumps(data)
    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(url, headers=headers, content=payload_data, timeout=30.0)
            response.raise_for_status()
            return response.json()
        except Exception:
            return None

@mcp.tool()
async def get_order_result(transaction_id: str, ctx: Context) -> Dict[str, Any] | str:
    """
    Retrieve an existing order transaction from FraudLabs Pro fraud detection system.
    
    It helps merchant to retrieve the validation result for an order transaction.
    
    Args:
        transaction_id: Unique transaction ID generated by Fraud Check API. Or order ID generated by your platform.
    
    Returns:
        A JSON string result includes:
        
        Location & Geography:
        Country, region, district, city, ZIP code, latitude & longitude, time zone.
        
        Network & Connectivity
        ISP (Internet Service Provider), domain, net speed, usage type.
        
        Mobile Information
        MNC (Mobile Network Code), MCC (Mobile Country Code), Mobile Brand.
        
        Username, Email address & Phone Number
        Validation result for email address and phone number.
        
        Credit Card
        Credit Card brand, type, issuing bank and country, and validation result.
        
        Device
        Device type, operating system, and validation result.
    """
    
    params = {"id": transaction_id}
    api_key = get_api_key()
    
    if api_key:
        params["key"] = api_key
    else:
        return(f"An API key is needed.")
    
    await ctx.session.send_log_message(
        level="info",
        data=f"[fraudlabspro] payload for order/result: '{params}'"
    )
    
    order_result = await make_request(urljoin(FLP_API_BASE, 'order/result'), params)
    return order_result if order_result else f"Unable to fetch result for Transaction id {transaction_id}."

@mcp.tool()
async def feedback_order(
    transaction_id: str, 
    action: str,
    note: Optional[str] = None,
    ctx: Context = None
) -> Dict[str, Any] | str:
    """
    Update status of a transaction from pending-manual-review to APPROVE, REJECT or REJECT_BLACKLIST.
    
    Args:
        transaction_id: Unique transaction Id generated by Fraud Check API.
        action: Perform APPROVE, REJECT, or REJECT_BLACKLIST action to transaction.
        note: Notes for the feedback request (optional).
    """
    if action.upper() not in ['APPROVE', 'REJECT', 'REJECT_BLACKLIST']:
        return "The action value must matched one of the following: APPROVE, REJECT, or REJECT_BLACKLIST"
    data = {"id": transaction_id, "action": action.upper()}
    if note: data["note"] = note
    
    api_key = get_api_key()
    
    if api_key:
        data["key"] = api_key
    else:
        return(f"An API key is needed.")
    
    await ctx.session.send_log_message(
        level="info",
        data=f"[fraudlabspro] order/feedback payload: '{data}'"
    )
    
    screen_result = await make_request_post(urljoin(FLP_API_BASE, 'order/feedback'), data)
    return screen_result if screen_result else "Unable to complete order feedback."

@mcp.tool()
async def screen_order(
    ip: str,
    last_name: Optional[str] = None,
    first_name: Optional[str] = None,
    bill_to: Optional[str] = None,
    bill_addr: Optional[str] = None,
    bill_city: Optional[str] = None,
    bill_state: Optional[str] = None,
    bill_country: Optional[str] = None,
    bill_zip_code: Optional[str] = None,
    ship_last_name: Optional[str] = None,
    ship_first_name: Optional[str] = None,
    ship_addr: Optional[str] = None,
    ship_city: Optional[str] = None,
    ship_state: Optional[str] = None,
    ship_country: Optional[str] = None,
    ship_zip_code: Optional[str] = None,
    user_phone: Optional[str] = None,
    email: Optional[str] = None,
    username: Optional[str] = None,
    bin_no: Optional[str] = None,
    card_hash: Optional[str] = None,
    user_order_id: Optional[str] = None,
    amount: Optional[str] = None,
    quantity: Optional[str] = None,
    currency: Optional[str] = None,
    department: Optional[str] = None,
    payment_gateway: Optional[str] = None,
    payment_mode: Optional[str] = None,
    coupon_code: Optional[str] = None,
    flp_checksum: Optional[str] = None,
    ctx: Context = None
) -> Dict[str, Any] | str:
    """
    Screen an order transaction for fraud.
    
    Args:
        ip: IP address of the user. It supports both IPv4 and IPv6 address format.
        last_name: User's last name (optional).
        first_name: User's first name (optional).
        bill_to: Billing details such as company name (optional).
        bill_addr: Street address of billing address (optional).
        bill_city: City of billing address (optional).
        bill_state: State of billing address (optional).
        bill_country: Country of billing address (optional).
        bill_zip_code: Postal or ZIP code of billing address (optional).
        ship_last_name: Recipient last name (optional).
        ship_first_name: Recipient first name (optional).
        ship_addr: Street address of shipping address (optional).
        ship_city: City of shipping address (optional).
        ship_state: State of shipping address (optional).
        ship_country: Country of shipping address (optional).
        ship_zip_code: Postal or ZIP code of shipping address (optional).
        user_phone: User's phone number in international format. (For example, +11234567890) (optional).
        email: User's email address (optional).
        username: The username used in the account sign up, if applicable (optional).
        bin_no: First 6 or 8 digits of credit card number to identify issuing bank (optional).
        card_hash: SHA2 hash of credit number (optional).
        user_order_id: Merchant identifier to uniquely identify a transaction. It supports maximum of 15 characters user order id input (optional).
        amount: Amount of the transaction (optional).
        quantity: Total quantity of the transaction (optional).
        currency: Currency code used in the transaction (optional).
        department: Merchant identifier to uniquely identify a product or service department (optional).
        payment_gateway: The name of payment gateway used to capture the payment (optional).
        payment_mode: Payment mode of transaction. Valid values: creditcard | paypal | cod | bankdeposit | giftcard | crypto | wired | others (optional).
        coupon_code: Coupon code applied to the order transaction (optional).
        flp_checksum: Checksum for the device validation (optional).
    """
    paramters = locals()
    exclude = {"ctx"}
    data = {k: v for k, v in paramters.items() if v is not None and k not in exclude}
    
    api_key = get_api_key()
    
    if api_key:
        data["key"] = api_key
    else:
        return(f"An API key is needed.")
    
    await ctx.session.send_log_message(
        level="info",
        data=f"[fraudlabspro] order/screen payload: '{data}'"
    )
    
    screen_result = await make_request_post(urljoin(FLP_API_BASE, 'order/screen'), data)
    return screen_result if screen_result else "Unable to complete order screening."

@mcp.tool()
async def get_user_result(user_transaction_id: str, ctx: Context) -> Dict[str, Any] | str:
    """
    Retrieve an existing transaction from FraudLabs Pro fraud detection system.
    
    It helps merchant to retrieve the validation result for an user transaction, for example a login event.
    
    Args:
        user_transaction_id: Unique User Screen ID generated by Screen User API.
    
    Returns:
        A JSON string result includes:
        
        Location & Geography:
        Country, region, district, city, ZIP code, latitude & longitude, time zone.
        
        Network & Connectivity
        ISP (Internet Service Provider), domain, net speed, usage type.
        
        Mobile Information
        MNC (Mobile Network Code), MCC (Mobile Country Code), Mobile Brand.
        
        Email address & Phone Number
        Validation result for email address and phone number.
        
        Device
        Device type, operating system, and validation result.
    """
    
    params = {"id": user_transaction_id}
    api_key = get_api_key()
    
    if api_key:
        params["key"] = api_key
    else:
        return(f"An API key is needed.")
    
    await ctx.session.send_log_message(
        level="info",
        data=f"[fraudlabspro] payload: '{params}'"
    )
    
    user_result = await make_request(urljoin(FLP_API_BASE, 'user/result'), params)
    return user_result if user_result else f"Unable to fetch result for Transaction id {user_transaction_id}."

@mcp.tool()
async def screen_user(
    email: str, 
    ip: str,
    flp_checksum: Optional[str] = None,
    last_name: Optional[str] = None,
    first_name: Optional[str] = None,
    phone: Optional[str] = None,
    ctx: Context = None
) -> Dict[str, Any] | str:
    """
    Screen a user transaction (e.g., login, registration) for fraud.
    
    Args:
        email: User's email address.
        ip: IP address of the user. It supports both IPv4 and IPv6 address format.
        flp_checksum: Checksum for the device validation (optional).
        last_name: User's last name (optional).
        first_name: User's first name (optional).
        phone: User's phone number in international format. (For example, +11234567890) (optional).
    """
    data = {"email": email, "ip": ip}
    if flp_checksum: data["flp_checksum"] = flp_checksum
    if last_name: data["last_name"] = last_name
    if first_name: data["first_name"] = first_name
    if phone: data["phone"] = phone
    
    api_key = get_api_key()
    
    if api_key:
        data["key"] = api_key
    else:
        return(f"An API key is needed.")
    
    await ctx.session.send_log_message(
        level="info",
        data=f"[fraudlabspro] user/screen payload: '{data}'"
    )
    
    screen_result = await make_request_post(urljoin(FLP_API_BASE, 'user/screen'), data)
    return screen_result if screen_result else "Unable to complete user screening."

@mcp.tool()
async def feedback_user(
    user_transaction_id: str, 
    action: str,
    reason: str,
    ctx: Context = None
) -> Dict[str, Any] | str:
    """
    Update status of a transaction from pending-manual-review to APPROVE, REJECT or REJECT_BLACKLIST.
    
    Args:
        user_transaction_id: Unique User Screen ID generated by Screen User API.
        action: Perform APPROVE, REJECT, or REJECT_BLACKLIST action to transaction.
        reason: Reasons for the feedback request
    """
    if action.upper() not in ['APPROVE', 'REJECT', 'REJECT_BLACKLIST']:
        return "The action value must matched one of the following: APPROVE, REJECT, or REJECT_BLACKLIST"
    data = {"id": user_transaction_id, "action": action.upper(), "reason": reason}
    
    api_key = get_api_key()
    
    if api_key:
        data["key"] = api_key
    else:
        return(f"An API key is needed.")
    
    await ctx.session.send_log_message(
        level="info",
        data=f"[fraudlabspro] user/feedback payload: '{data}'"
    )
    
    screen_result = await make_request_post(urljoin(FLP_API_BASE, 'user/feedback'), data)
    return screen_result if screen_result else "Unable to complete user feedback."

if __name__ == "__main__":
    mcp.run(transport='stdio')
